# DEV ONLY
version: '3'
services:
    nginx:
        build:
            context: docker/dev/nginx
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - '${APP_PORT-80}:80'
        volumes:
            - './:/var/www/html'
        networks:
            - tacos
        depends_on:
            - app

    app:
        build:
            context: ./docker/dev/php
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1001}
        image: tacoview/app:dev
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - tacos
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailhog
            - minio

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'tacos-mysql:/var/lib/mysql'
            - './docker/dev/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - tacos
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'tacos-redis:/data'
        networks:
            - tacos
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'tacos-meilisearch:/meili_data'
        environment:
            MEILI_MASTER_KEY: '${MEILI_MASTER_KEY}'
        networks:
            - tacos
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - tacos

    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: 'tacos'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - 'tacos-minio:/data/minio'
        networks:
            - tacos
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s

networks:
    tacos:
        driver: bridge
volumes:
    tacos-mysql:
        driver: local
    tacos-redis:
        driver: local
    tacos-meilisearch:
        driver: local
    tacos-minio:
        driver: local
